### ISSUE TITLE
Regression: Can't resume chains anymore

### ISSUE THREAD

**Issue by vivianmiranda** [CobayaSampler/cobaya#16]
Hi! 

Since I updated Cobaya with the last few commits - I can't resume chains anymore - even with -r option the chains are deleted - here my error message and yams files

[test.txt](https://github.com/CobayaSampler/cobaya/files/2664831/test.txt)
[out_55640348.txt](https://github.com/CobayaSampler/cobaya/files/2664834/out_55640348.txt)
[mcmc.txt](https://github.com/CobayaSampler/cobaya/files/2664837/mcmc.txt)

**Comment by JesusTorrado** [comment]
Hi Vivian,

I have been doing some tests but have had no problem resuming with MCMC or PolyChord.

The last line in `out_...` suggests that resuming is not possible because the previous run was send with a different number of MPI processes from the new one. Do you think that's the case? If it is, I am afraid, this is a limitation that is hard to tackle right now.

Also, I am a little surprised that the chains files are deleted. This should never happen! Does it delete the chains when it tries to resume but fails?

(Sorry for the delay with this! I have too many projects going on right now)

**Comment by vivianmiranda** [comment]
On Dec 14, 2018, at 10:02 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Vivian,

I have been doing some tests but have had no problem resuming with MCMC or PolyChord.

The last line in out_... suggests that resuming is not possible because the previous run was send with a different number of MPI processes from the new one. Do you think that's the case? If it is, I am afraid, this is a limitation that is hard to tackle right now.

Also, I am a little surprised that the chains files are deleted. This should never happen! Does it delete the chains when it tries to resume but fails?

(Sorry for the delay with this! I have too many projects going on right now)


It does delete them!

I will try to check - but I was pretty sure the mpi was keeping the same number of processes

Best
Vivian

**Comment by vivianmiranda** [comment]
I just checked

timeout 127800 mpirun -np 4 cobaya-run test4.yaml -r

I was using the same number of MPI processes

The problem is that Cobaya is deleting the chains before even checking the number of MPI processes through the number of files!

Thx for helping that - I can’t do anything in my project with this problem.

On Dec 14, 2018, at 10:04 AM, Miranda, Vivian - (vivianmiranda) <vivianmiranda@email.arizona.edu<mailto:vivianmiranda@email.arizona.edu>> wrote:



On Dec 14, 2018, at 10:02 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Vivian,

I have been doing some tests but have had no problem resuming with MCMC or PolyChord.

The last line in out_... suggests that resuming is not possible because the previous run was send with a different number of MPI processes from the new one. Do you think that's the case? If it is, I am afraid, this is a limitation that is hard to tackle right now.

Also, I am a little surprised that the chains files are deleted. This should never happen! Does it delete the chains when it tries to resume but fails?

(Sorry for the delay with this! I have too many projects going on right now)


It does delete them!

I will try to check - but I was pretty sure the mpi was keeping the same number of processes

Best
Vivian

**Comment by JesusTorrado** [comment]
You are right, sorry! It does in the case in which there is a different number of MPI processes. This should definitely not happen! Fixing it right now! I hope you haven't lost anything important :(

**Comment by vivianmiranda** [comment]
A coupled of thousand cpu-hours

No worries!



On Dec 14, 2018, at 10:10 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


You are right, sorry! It does in the case in which there is a different number of MPI processes. This should definitely not happen! Fixing it right now! I hope you haven't lost anything important :(

**Comment by JesusTorrado** [comment]
Wow, I am really very sorry!!!

**Comment by vivianmiranda** [comment]
No problem

I am burning them to test your code so Cobaya-Cosmolike can rule!

:)

Your job is incredible

Did you commit the changes? I can’t see them


On Dec 14, 2018, at 10:15 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Wow, I am really very sorry!!!

**Comment by JesusTorrado** [comment]
Thanks! :)

Still debugging: it's a tricky one! But won't close for today until I get it done. Stay tuned!

**Comment by JesusTorrado** [comment]
Done! It was a error in my MPI-wrapping of the `output` class. I am very grateful to you for suffering through all these bugs!

On Monday, I'll try to incorporate your fix for the new Planck likelihood code, so that you don't need to keep your own version.

**Comment by vivianmiranda** [comment]
I am not suffering! I am enjoying your new very cool code! I am glad I can contribute in some small ways!

**Comment by vivianmiranda** [comment]
Hi I still get problems. Now this

Traceback (most recent call last):
  File "/scratch/midway2/viniciusvmb/krause/cosmo_cobaya/bin/cobaya-run", line 11, in <module>
    load_entry_point('cobaya', 'console_scripts', 'cobaya-run')()
  File "/scratch/midway2/viniciusvmb/krause/cosmo_cobaya/cosmolike_core/cobaya/cobaya/run.py", line 126, in run_script
    run(info)
  File "/scratch/midway2/viniciusvmb/krause/cosmo_cobaya/cosmolike_core/cobaya/cobaya/run.py", line 45, in run
    _force_reproducible, _force_reproducible_default))
  File "/scratch/midway2/viniciusvmb/krause/cosmo_cobaya/cosmolike_core/cobaya/cobaya/output.py", line 208, in get_Output
    return Output(*args, **kwargs)
  File "/scratch/midway2/viniciusvmb/krause/cosmo_cobaya/cosmolike_core/cobaya/cobaya/output.py", line 191, in __init__
    setattr(self, var, comm.bcast(getattr(self, var), root=0))
AttributeError: 'Output_MPI' object has no attribute 'resuming'

Best

**Comment by vivianmiranda** [comment]
And if I run without mpirun I get the error

Traceback (most recent call last):
  File "/scratch/midway2/viniciusvmb/krause/cosmo_cobaya/bin/cobaya-run", line 11, in <module>
    load_entry_point('cobaya', 'console_scripts', 'cobaya-run')()
  File "/scratch/midway2/viniciusvmb/krause/cosmo_cobaya/cosmolike_core/cobaya/cobaya/run.py", line 126, in run_script
    run(info)
  File "/scratch/midway2/viniciusvmb/krause/cosmo_cobaya/cosmolike_core/cobaya/cobaya/run.py", line 66, in run
    modules=info.get(_path_install)) as sampler:
  File "/scratch/midway2/viniciusvmb/krause/cosmo_cobaya/cosmolike_core/cobaya/cobaya/sampler.py", line 202, in get_sampler
    info_sampler[name], posterior, output_file, resume=resume, modules=modules)
  File "/scratch/midway2/viniciusvmb/krause/cosmo_cobaya/cosmolike_core/cobaya/cobaya/sampler.py", line 161, in __init__
    self.initialize()
  File "/scratch/midway2/viniciusvmb/krause/cosmo_cobaya/cosmolike_core/cobaya/cobaya/samplers/mcmc/mcmc.py", line 65, in initialize
    get_mpi_comm().barrier()
AttributeError: 'NoneType' object has no attribute 'barrier'

So I can't use Cobaya at all now

**Comment by vivianmiranda** [comment]
I was able to create the following workaround on output.py

<img width="775" alt="screen shot 2018-12-14 at 4 29 44 pm" src="https://user-images.githubusercontent.com/3210728/50035152-c4c5cf80-ffbd-11e8-90b1-88ff89059148.png">

**Comment by JesusTorrado** [comment]
Thanks for the fix, and sorry! Nothing goods come out of a last-minute Friday-evening attempt of a bugfix.

**Comment by vivianmiranda** [comment]
You’re welcome. Not sure if it was the best fix - but it worked!



On Dec 17, 2018, at 4:22 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the fix, and sorry! Nothing goods come out of a last-minute Friday-evening attempt of a bugfix.
