### ISSUE TITLE
planck_2018_lowl.EE with PolyChord

### ISSUE THREAD

**Issue by lukashergt** [CobayaSampler/cobaya#43]
While running PolyChord with planck_2018_lowl.TT and with planck_2018_highl_plik.TT works, I get the following error as soon as I add planck_2018_lowl.EE to the likelihoods (full debug output further below):

```
 2019-09-30 16:54:06,064 [planck_2018_lowl.EE] Got parameters {'A_planck': 1.0059452468116512}
 2019-09-30 16:54:06,071 [exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/likelihood.py", line 129, in _logp_cached
    i_state = next(i for i in range(self.n_states)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lh561/.virtualenvs/py36env/bin/cobaya-run", line 11, in <module>
    load_entry_point('cobaya', 'console_scripts', 'cobaya-run')()
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/run.py", line 154, in run_script
    run(info)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/run.py", line 87, in run
    sampler.run()
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/sampler.py", line 182, in __exit__
    self.close(exception_type, exception_value, traceback)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/run.py", line 87, in run
    sampler.run()
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/samplers/polychord/polychord.py", line 233, in run
    self.pc_prior, self.dumper)
  File "/home/lh561/.virtualenvs/py36env/lib/python3.6/site-packages/pypolychord-1.16-py3.6-linux-x86_64.egg/pypolychord/__init__.py", line 231, in run_polychord
    settings.seed)
  File "/home/lh561/.virtualenvs/py36env/lib/python3.6/site-packages/pypolychord-1.16-py3.6-linux-x86_64.egg/pypolychord/__init__.py", line 192, in wrap_loglikelihood
    logL, phi[:] = loglikelihood(theta)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/samplers/polychord/polychord.py", line 218, in logpost
    self.model.logposterior(params_values))
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/model.py", line 280, in logposterior
    make_finite=make_finite, cached=cached, _no_check=True)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/model.py", line 186, in loglikes
    _derived=_derived, cached=cached)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/likelihood.py", line 360, in logps
    _derived=this_derived_dict, cached=cached, **this_params_dict)]
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/likelihood.py", line 146, in _logp_cached
    self.states[i_state]["logp"] = self.logp(_derived=_derived, **params_values)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/likelihoods/_base_classes/_planck_clik_prototype.py", line 139, in logp
    loglike = self.clik(self.vector)[0]
  File "lkl.pyx", line 89, in clik.lkl.clik.__call__
clik.lkl.CError: <unprintable CError object>
-------------------------------------------------------------
```

Running with the `mcmc` sampler seems to work fine. Hence, I suspected that it might have to do with extreme values of the `A_planck` parameter (i.e. the tails of the default Gaussian prior) at first. However, even upon switching to a narrow uniform prior on `A_planck`, the error persists.

**Anybody an idea what might be causing this?** The error message `<unprintable CError object>` is rather cryptic to me...

---

Full debug output:
```
(py36env) lh561@login-e-13:~/Documents/Projects/CobayaPrj$cobaya-run -f input/pc32_camb_p18_TTTEEElowTE_lcdm.yaml -d
 2019-09-30 16:54:04,838 [output] Output to be read-from/written-into folder 'chains/planck_2018/lcdm/pc32_camb_p18_TTTEEElowTE_lcdm', with prefix 'pc32_camb_p18_TTTEEElowTE_lcdm'
 2019-09-30 16:54:04,839 [output] Found existing products with the requested ouput prefix: 'chains/planck_2018/lcdm/pc32_camb_p18_TTTEEElowTE_lcdm/pc32_camb_p18_TTTEEElowTE_lcdm'
 2019-09-30 16:54:04,840 [output] Deleting previous chain ('force' was requested).
 2019-09-30 16:54:04,944 [input] Parameter 'A_planck' multiply defined.
 2019-09-30 16:54:04,944 [input] Parameter 'A_planck' multiply defined.
 2019-09-30 16:54:04,979 [run] Input info updated with defaults (dumped to YAML):
theory:
  camb:
    extra_args:
      halofit_version: mead
      bbn_predictor: PArthENoPE_880.2_standard.dat
      lens_potential_accuracy: 1
      num_massive_neutrinos: 1
      nnu: 3.046
      theta_H0_range:
      - 20
      - 100
    path: null
    renames:
      omegabh2: ombh2
      omegach2: omch2
      omegal: omega_de
      omegak: omk
      yhe: YHe
      yheused: YHe
      YpBBN: Y_p
      zrei: zre
    speed: 0.3
    stop_at_error: false
    use_planck_names: false
likelihood:
  planck_2018_lowl.TT:
    clik_file: baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik
    params:
    - A_planck
    path: null
    product_id: '151902'
    renames:
    - lowl
    speed: 3000
  planck_2018_lowl.EE:
    clik_file: baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik
    params:
    - A_planck
    path: null
    product_id: '151902'
    renames:
    - lowE
    speed: 4000
  planck_2018_highl_plik.TTTEEE:
    clik_file: baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik
    params:
    - A_planck
    - calib_100T
    - calib_217T
    - A_pol
    - calib_100P
    - calib_143P
    - calib_217P
    - cib_index
    - A_cib_217
    - xi_sz_cib
    - A_sz
    - ksz_norm
    - gal545_A_100
    - gal545_A_143
    - gal545_A_143_217
    - gal545_A_217
    - A_sbpx_100_100_TT
    - A_sbpx_143_143_TT
    - A_sbpx_143_217_TT
    - A_sbpx_217_217_TT
    - ps_A_100_100
    - ps_A_143_143
    - ps_A_143_217
    - ps_A_217_217
    - galf_TE_index
    - galf_TE_A_100
    - galf_TE_A_100_143
    - galf_TE_A_100_217
    - galf_TE_A_143
    - galf_TE_A_143_217
    - galf_TE_A_217
    - galf_EE_index
    - galf_EE_A_100
    - galf_EE_A_100_143
    - galf_EE_A_100_217
    - galf_EE_A_143
    - galf_EE_A_143_217
    - galf_EE_A_217
    - A_cnoise_e2e_100_100_EE
    - A_cnoise_e2e_143_143_EE
    - A_cnoise_e2e_217_217_EE
    - A_sbpx_100_100_EE
    - A_sbpx_100_143_EE
    - A_sbpx_100_217_EE
    - A_sbpx_143_143_EE
    - A_sbpx_143_217_EE
    - A_sbpx_217_217_EE
    path: null
    product_id: '151902'
    renames:
    - plikHM_TTTEEE
    speed: 7
sampler:
  polychord:
    base_dir: raw_polychord_output
    blocking:
    - - 1
      - - ombh2
        - omch2
        - theta_MC_100
        - tau
        - logA
        - ns
    - - 10
      - - A_planck
    - - 20
      - - A_cib_217
        - xi_sz_cib
        - A_sz
        - ps_A_100_100
        - ps_A_143_143
        - ps_A_143_217
        - ps_A_217_217
        - ksz_norm
        - gal545_A_100
        - gal545_A_143
        - gal545_A_143_217
        - gal545_A_217
        - calib_100T
        - calib_217T
        - galf_TE_A_100_143
        - galf_TE_A_143_217
        - galf_TE_A_100_217
        - galf_TE_A_100
        - galf_TE_A_143
        - galf_TE_A_217
    boost_posterior: 0
    callback_function: null
    cluster_posteriors: true
    compression_factor: 0.36787944117144233
    confidence_for_unbounded: 0.9999995
    do_clustering: true
    equals: true
    feedback: null
    file_root: null
    logzero: -1.0e+300
    max_ndead: .inf
    nlive: 32
    nprior: null
    num_repeats: 2
    path: global
    posteriors: true
    precision_criterion: 0.001
    read_resume: true
    seed: null
    write_dead: true
    write_live: true
    write_resume: true
    write_stats: true
prior:
  SZ: 'lambda ksz_norm, A_sz: stats.norm.logpdf(ksz_norm+1.6*A_sz, loc=9.5, scale=3.0)'
params:
  logA:
    prior:
      min: 2.5
      max: 3.7
    ref:
      dist: norm
      loc: 3.05
      scale: 0.001
    proposal: 0.001
    latex: \log(10^{10} A_\mathrm{s})
    drop: true
  As:
    value: 'lambda logA: 1e-10*np.exp(logA)'
    latex: A_\mathrm{s}
    derived: true
  ns:
    prior:
      min: 0.885
      max: 1.04
    ref:
      dist: norm
      loc: 0.965
      scale: 0.004
    proposal: 0.002
    latex: n_\mathrm{s}
  theta_MC_100:
    prior:
      min: 1.03
      max: 1.05
    ref:
      dist: norm
      loc: 1.04
      scale: 0.0004
    proposal: 0.0002
    latex: 100\theta_\mathrm{MC}
    drop: true
    renames: theta
  cosmomc_theta:
    value: 'lambda theta_MC_100: 1.e-2*theta_MC_100'
    derived: false
  H0:
    latex: H_0
    min: 20
    max: 100
    derived: true
  ombh2:
    prior:
      min: 0.019
      max: 0.025
    ref:
      dist: norm
      loc: 0.0224
      scale: 0.0001
    proposal: 0.0001
    latex: \Omega_\mathrm{b} h^2
    renames:
    - omegabh2
  omch2:
    prior:
      min: 0.095
      max: 0.145
    ref:
      dist: norm
      loc: 0.12
      scale: 0.001
    proposal: 0.0005
    latex: \Omega_\mathrm{c} h^2
    renames:
    - omegach2
  omegam:
    latex: \Omega_\mathrm{m}
    derived: true
  omegamh2:
    derived: 'lambda omegam, H0: omegam*(H0/100)**2'
    latex: \Omega_\mathrm{m} h^2
  mnu:
    value: 0.06
  omega_de:
    latex: \Omega_\Lambda
    derived: true
    renames:
    - omegal
  YHe:
    latex: Y_\mathrm{P}
    derived: true
    renames:
    - yheused
    - yhe
  Y_p:
    latex: Y_P^\mathrm{BBN}
    derived: true
    renames:
    - YpBBN
  DHBBN:
    derived: 'lambda DH: 10**5*DH'
    latex: 10^5 \mathrm{D}/\mathrm{H}
  tau:
    prior:
      min: 0.01
      max: 0.4
    ref:
      dist: norm
      loc: 0.055
      scale: 0.006
    proposal: 0.003
    latex: \tau_\mathrm{reio}
  zre:
    latex: z_\mathrm{re}
    derived: true
    renames:
    - zrei
  sigma8:
    latex: \sigma_8
    derived: true
  s8h5:
    derived: 'lambda sigma8, H0: sigma8*(H0*1e-2)**(-0.5)'
    latex: \sigma_8/h^{0.5}
  s8omegamp5:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.5'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.5}
  s8omegamp25:
    derived: 'lambda sigma8, omegam: sigma8*omegam**0.25'
    latex: \sigma_8 \Omega_\mathrm{m}^{0.25}
  A:
    derived: 'lambda As: 1e9*As'
    latex: 10^9 A_\mathrm{s}
  clamp:
    derived: 'lambda As, tau: 1e9*As*np.exp(-2*tau)'
    latex: 10^9 A_\mathrm{s} e^{-2\tau}
  age:
    latex: '{\rm{Age}}/\mathrm{Gyr}'
    derived: true
  rdrag:
    latex: r_\mathrm{drag}
    derived: true
  chi2__CMB:
    derived: 'lambda chi2__planck_2018_lowl_TT, chi2__planck_2018_lowl_EE, chi2__planck_2018_highl_plik_TTTEEE:
      sum([chi2__planck_2018_lowl_TT, chi2__planck_2018_lowl_EE, chi2__planck_2018_highl_plik_TTTEEE])'
    latex: \chi^2_\mathrm{CMB}
  A_planck:
    prior:
      dist: norm
      loc: 1
      scale: 0.0025
    ref:
      dist: norm
      loc: 1
      scale: 0.002
    proposal: 0.0005
    latex: y_\mathrm{cal}
    renames: calPlanck
  calib_100T:
    prior:
      dist: norm
      loc: 1.0002
      scale: 0.0007
    ref:
      dist: norm
      loc: 1.0002
      scale: 0.001
    proposal: 0.0005
    latex: c_{100}
    renames: cal0
  calib_217T:
    prior:
      dist: norm
      loc: 0.99805
      scale: 0.00065
    ref:
      dist: norm
      loc: 0.99805
      scale: 0.001
    proposal: 0.0005
    latex: c_{217}
    renames: cal2
  A_pol:
    value: 1
  calib_100P:
    value: 1.021
  calib_143P:
    value: 0.966
  calib_217P:
    value: 1.04
  cib_index:
    value: -1.3
  A_cib_217:
    prior:
      dist: uniform
      min: 0
      max: 200
    ref:
      dist: norm
      loc: 67
      scale: 10
    proposal: 1.2
    latex: A^\mathrm{CIB}_{217}
    renames: acib217
  xi_sz_cib:
    prior:
      dist: uniform
      min: 0
      max: 1
    ref:
      dist: halfnorm
      loc: 0
      scale: 0.1
    proposal: 0.1
    latex: \xi^{\mathrm{tSZ}\times\mathrm{CIB}}
    renames: xi
  A_sz:
    prior:
      dist: uniform
      min: 0
      max: 10
    ref:
      dist: norm
      loc: 7
      scale: 2
    proposal: 0.6
    latex: A^\mathrm{tSZ}_{143}
    renames: asz143
  ksz_norm:
    prior:
      dist: uniform
      min: 0
      max: 10
    ref:
      dist: halfnorm
      loc: 0
      scale: 3
    proposal: 1
    latex: A^\mathrm{kSZ}
    renames: aksz
  gal545_A_100:
    prior:
      dist: norm
      loc: 8.6
      scale: 2
    ref:
      dist: norm
      loc: 7
      scale: 2
    proposal: 1
    latex: A^\mathrm{dustTT}_{100}
    renames: kgal100
  gal545_A_143:
    prior:
      dist: norm
      loc: 10.6
      scale: 2
    ref:
      dist: norm
      loc: 9
      scale: 2
    proposal: 1
    latex: A^\mathrm{dustTT}_{143}
    renames: kgal143
  gal545_A_143_217:
    prior:
      dist: norm
      loc: 23.5
      scale: 8.5
    ref:
      dist: norm
      loc: 21
      scale: 4
    proposal: 1.5
    latex: A^\mathrm{dustTT}_{\mathrm{143}\times\mathrm{217}}
    renames: kgal143217
  gal545_A_217:
    prior:
      dist: norm
      loc: 91.9
      scale: 20
    ref:
      dist: norm
      loc: 80
      scale: 15
    proposal: 2
    latex: A^\mathrm{dustTT}_{217}
    renames: kgal217
  A_sbpx_100_100_TT:
    value: 1
  A_sbpx_143_143_TT:
    value: 1
  A_sbpx_143_217_TT:
    value: 1
  A_sbpx_217_217_TT:
    value: 1
  ps_A_100_100:
    prior:
      dist: uniform
      min: 0
      max: 400
    ref:
      dist: norm
      loc: 257
      scale: 24
    proposal: 17
    latex: A^\mathrm{PS}_{100}
    renames: aps100
  ps_A_143_143:
    prior:
      dist: uniform
      min: 0
      max: 400
    ref:
      dist: norm
      loc: 47
      scale: 10
    proposal: 3
    latex: A^\mathrm{PS}_{143}
    renames: aps143
  ps_A_143_217:
    prior:
      dist: uniform
      min: 0
      max: 400
    ref:
      dist: norm
      loc: 40
      scale: 12
    proposal: 2
    latex: A^\mathrm{PS}_{\mathrm{143}\times\mathrm{217}}
    renames: aps143217
  ps_A_217_217:
    prior:
      dist: uniform
      min: 0
      max: 400
    ref:
      dist: norm
      loc: 104
      scale: 13
    proposal: 2.5
    latex: A^\mathrm{PS}_{217}
    renames: aps217
  galf_TE_index:
    value: -2.4
  galf_TE_A_100:
    prior:
      dist: norm
      loc: 0.13
      scale: 0.042
    ref:
      dist: norm
      loc: 0.13
      scale: 0.1
    proposal: 0.1
    latex: A^\mathrm{dustTE}_{100}
    renames: galfTE100
  galf_TE_A_100_143:
    prior:
      dist: norm
      loc: 0.13
      scale: 0.036
    ref:
      dist: norm
      loc: 0.13
      scale: 0.1
    proposal: 0.1
    latex: A^\mathrm{dustTE}_{\mathrm{100}\times\mathrm{143}}
    renames: galfTE100143
  galf_TE_A_100_217:
    prior:
      dist: norm
      loc: 0.46
      scale: 0.09
    ref:
      dist: norm
      loc: 0.46
      scale: 0.1
    proposal: 0.1
    latex: A^\mathrm{dustTE}_{\mathrm{100}\times\mathrm{217}}
    renames: galfTE100217
  galf_TE_A_143:
    prior:
      dist: norm
      loc: 0.207
      scale: 0.072
    ref:
      dist: norm
      loc: 0.207
      scale: 0.1
    proposal: 0.1
    latex: A^\mathrm{dustTE}_{143}
    renames: galfTE143
  galf_TE_A_143_217:
    prior:
      dist: norm
      loc: 0.69
      scale: 0.09
    ref:
      dist: norm
      loc: 0.69
      scale: 0.1
    proposal: 0.1
    latex: A^\mathrm{dustTE}_{\mathrm{143}\times\mathrm{217}}
    renames: galfTE143217
  galf_TE_A_217:
    prior:
      dist: norm
      loc: 1.938
      scale: 0.54
    ref:
      dist: norm
      loc: 1.938
      scale: 0.2
    proposal: 0.2
    latex: A^\mathrm{dustTE}_{217}
    renames: galfTE217
  galf_EE_index:
    value: -2.4
  galf_EE_A_100:
    value: 0.055
    latex: A^\mathrm{dustEE}_{100}
    renames: galfEE100
  galf_EE_A_100_143:
    value: 0.04
    latex: A^\mathrm{dustEE}_{\mathrm{100}\times\mathrm{143}}
    renames: galfEE100143
  galf_EE_A_100_217:
    value: 0.094
    latex: A^\mathrm{dustEE}_{\mathrm{100}\times\mathrm{217}}
    renames: galfEE100217
  galf_EE_A_143:
    value: 0.086
    latex: A^\mathrm{dustEE}_{143}
    renames: galfEE143
  galf_EE_A_143_217:
    value: 0.21
    latex: A^\mathrm{dustEE}_{\mathrm{143}\times\mathrm{217}}
    renames: galfEE143217
  galf_EE_A_217:
    value: 0.7
    latex: A^\mathrm{dustEE}_{217}
    renames: galfEE217
  A_cnoise_e2e_100_100_EE:
    value: 1
  A_cnoise_e2e_143_143_EE:
    value: 1
  A_cnoise_e2e_217_217_EE:
    value: 1
  A_sbpx_100_100_EE:
    value: 1
  A_sbpx_100_143_EE:
    value: 1
  A_sbpx_100_217_EE:
    value: 1
  A_sbpx_143_143_EE:
    value: 1
  A_sbpx_143_217_EE:
    value: 1
  A_sbpx_217_217_EE:
    value: 1
output: pc32_camb_p18_TTTEEElowTE_lcdm
modules: /rds/user/lh561/hpc-work/data/CobayaData/modules
debug: true
resume: false
force: true

 2019-09-30 16:54:05,072 [prior] Loading external prior 'SZ' from: 'lambda ksz_norm, A_sz: stats.norm.logpdf(ksz_norm+1.6*A_sz, loc=9.5, scale=3.0)'
 2019-09-30 16:54:05,072 [prior] *WARNING* External prior 'SZ' loaded. Mind that it might not be normalized!
 2019-09-30 16:54:05,073 [likelihood] Parameters were assigned as follows:
 2019-09-30 16:54:05,073 [likelihood] - 'planck_2018_lowl.TT':
 2019-09-30 16:54:05,073 [likelihood]      Input:  ['A_planck']
 2019-09-30 16:54:05,073 [likelihood]      Output: []
 2019-09-30 16:54:05,073 [likelihood] - 'planck_2018_lowl.EE':
 2019-09-30 16:54:05,073 [likelihood]      Input:  ['A_planck']
 2019-09-30 16:54:05,073 [likelihood]      Output: []
 2019-09-30 16:54:05,073 [likelihood] - 'planck_2018_highl_plik.TTTEEE':
 2019-09-30 16:54:05,073 [likelihood]      Input:  ['A_planck', 'calib_100T', 'calib_217T', 'A_pol', 'calib_100P', 'calib_143P', 'calib_217P', 'cib_index', 'A_cib_217', 'xi_sz_cib', 'A_sz', 'ksz_norm', 'gal545_A_100', 'gal545_A_143', 'gal545_A_143_217', 'gal545_A_217', 'A_sbpx_100_100_TT', 'A_sbpx_143_143_TT', 'A_sbpx_143_217_TT', 'A_sbpx_217_217_TT', 'ps_A_100_100', 'ps_A_143_143', 'ps_A_143_217', 'ps_A_217_217', 'galf_TE_index', 'galf_TE_A_100', 'galf_TE_A_100_143', 'galf_TE_A_100_217', 'galf_TE_A_143', 'galf_TE_A_143_217', 'galf_TE_A_217', 'galf_EE_index', 'galf_EE_A_100', 'galf_EE_A_100_143', 'galf_EE_A_100_217', 'galf_EE_A_143', 'galf_EE_A_143_217', 'galf_EE_A_217', 'A_cnoise_e2e_100_100_EE', 'A_cnoise_e2e_143_143_EE', 'A_cnoise_e2e_217_217_EE', 'A_sbpx_100_100_EE', 'A_sbpx_100_143_EE', 'A_sbpx_100_217_EE', 'A_sbpx_143_143_EE', 'A_sbpx_143_217_EE', 'A_sbpx_217_217_EE']
 2019-09-30 16:54:05,073 [likelihood]      Output: []
 2019-09-30 16:54:05,073 [likelihood] - 'theory':
 2019-09-30 16:54:05,073 [likelihood]      Input:  ['As', 'ns', 'cosmomc_theta', 'ombh2', 'omch2', 'mnu', 'tau']
 2019-09-30 16:54:05,073 [likelihood]      Output: ['H0', 'omegam', 'omega_de', 'YHe', 'Y_p', 'zre', 'sigma8', 'age', 'rdrag', 'DH']
 2019-09-30 16:54:05,074 [camb] *local* CAMB not found at /rds/user/lh561/hpc-work/data/CobayaData/modules/code/CAMB
 2019-09-30 16:54:05,074 [camb] Importing *global* CAMB.
 2019-09-30 16:54:05,129 [planck_2018_lowl.TT] Importing clik from /rds/user/lh561/hpc-work/data/CobayaData/modules/code/planck
----
clik version 3be036bbb4f9
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/rds/user/lh561/hpc-work/data/CobayaData/modules/data/planck_2018/baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----
Initializing SimAll
----
clik version 3be036bbb4f9
  simall simall_EE_BB_TE
Checking likelihood '/rds/user/lh561/hpc-work/data/CobayaData/modules/data/planck_2018/baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
----
clik version 3be036bbb4f9
  smica
Checking likelihood '/rds/user/lh561/hpc-work/data/CobayaData/modules/data/planck_2018/baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34054e-07)
----
 2019-09-30 16:54:05,560 [likelihood] The theory code will compute the following products, requested by the likelihoods: ['H0', 'omegam', 'omega_de', 'YHe', 'Y_p', 'zre', 'sigma8', 'age', 'rdrag', 'DH', 'Cl']
 2019-09-30 16:54:05,606 [polychord] Initializing
 2019-09-30 16:54:05,606 [polychord] Importing *global* PolyChord.
 2019-09-30 16:54:05,613 [polychord] Storing raw PolyChord output in 'chains/planck_2018/lcdm/pc32_camb_p18_TTTEEElowTE_lcdm/raw_polychord_output'.
 2019-09-30 16:54:05,614 [prior] *WARNING* There are unbounded parameters. Prior bounds are given at 0.9999995 confidence level. Beware of likelihood modes at the edge of the prior
 2019-09-30 16:54:05,621 [polychord] Calling PolyChord with arguments:
 2019-09-30 16:54:05,621 [polychord]   base_dir: chains/planck_2018/lcdm/pc32_camb_p18_TTTEEElowTE_lcdm/raw_polychord_output
 2019-09-30 16:54:05,621 [polychord]   boost_posterior: 0
 2019-09-30 16:54:05,621 [polychord]   cluster_dir: chains/planck_2018/lcdm/pc32_camb_p18_TTTEEElowTE_lcdm/raw_polychord_output/clusters
 2019-09-30 16:54:05,621 [polychord]   cluster_posteriors: True
 2019-09-30 16:54:05,621 [polychord]   compression_factor: 0.36787944117144233
 2019-09-30 16:54:05,621 [polychord]   do_clustering: True
 2019-09-30 16:54:05,621 [polychord]   equals: True
 2019-09-30 16:54:05,621 [polychord]   feedback: 2
 2019-09-30 16:54:05,622 [polychord]   file_root: pc32_camb_p18_TTTEEElowTE_lcdm
 2019-09-30 16:54:05,622 [polychord]   grade_dims: [6, 1, 20]
 2019-09-30 16:54:05,622 [polychord]   grade_frac: [12, 20, 800]
 2019-09-30 16:54:05,622 [polychord]   logzero: -1e+300
 2019-09-30 16:54:05,622 [polychord]   max_ndead: -1
 2019-09-30 16:54:05,622 [polychord]   maximise: False
 2019-09-30 16:54:05,622 [polychord]   nfail: -1
 2019-09-30 16:54:05,622 [polychord]   nlive: 32
 2019-09-30 16:54:05,622 [polychord]   nlives: {}
 2019-09-30 16:54:05,622 [polychord]   nprior: -1
 2019-09-30 16:54:05,622 [polychord]   num_repeats: 2
 2019-09-30 16:54:05,622 [polychord]   posteriors: True
 2019-09-30 16:54:05,622 [polychord]   precision_criterion: 0.001
 2019-09-30 16:54:05,622 [polychord]   read_resume: False
 2019-09-30 16:54:05,622 [polychord]   seed: -1
 2019-09-30 16:54:05,622 [polychord]   write_dead: True
 2019-09-30 16:54:05,622 [polychord]   write_live: True
 2019-09-30 16:54:05,622 [polychord]   write_paramnames: False
 2019-09-30 16:54:05,622 [polychord]   write_prior: True
 2019-09-30 16:54:05,622 [polychord]   write_resume: True
 2019-09-30 16:54:05,622 [polychord]   write_stats: True
 2019-09-30 16:54:05,622 [polychord] Sampling!
PolyChord: MPI is already initilised, not initialising, and will not finalize

PolyChord: Next Generation Nested Sampling
copyright: Will Handley, Mike Hobson & Anthony Lasenby
  version: 1.16
  release: 1st March 2019
    email: wh260@mrao.cam.ac.uk

Run Settings
nlive    :      32
nDims    :      27
nDerived :      23
Doing Clustering
Generating equally weighted posteriors
Generating weighted posteriors
Clustering on posteriors
Writing a resume file tochains/planck_2018/lcdm/pc32_camb_p18_TTTEEElowTE_lcdm/raw_polychord_output/pc32_camb_p18_TTTEEElowTE_lcdm.resume

generating live points

 2019-09-30 16:54:05,626 [model] Posterior to be computed for parameters {'logA': 3.5037013816249623, 'ns': 0.9112045733967743, 'theta_MC_100': 1.041265037924763, 'ombh2': 0.021621996540981202, 'omch2': 0.14176980838432607, 'tau': 0.3095362460289987, 'A_planck': 1.0059452468116512, 'calib_100T': 0.9987164276517926, 'calib_217T': 0.9969867491925797, 'A_cib_217': 161.1045890924937, 'xi_sz_cib': 0.2051553164786664, 'A_sz': 5.386228462601731, 'ksz_norm': 6.765631397757046, 'gal545_A_100': 13.871489482728224, 'gal545_A_143': 10.6969527157267, 'gal545_A_143_217': 20.8161734334329, 'gal545_A_217': 178.5397415906308, 'ps_A_100_100': 130.0920806163113, 'ps_A_143_143': 89.60662764337052, 'ps_A_143_217': 164.5425707037178, 'ps_A_217_217': 84.67800468096046, 'galf_TE_A_100': 0.0490355091419101, 'galf_TE_A_100_143': 0.037890502727434563, 'galf_TE_A_100_217': 0.7121590683248342, 'galf_TE_A_143': 0.328393151407387, 'galf_TE_A_143_217': 1.0608083053493131, 'galf_TE_A_217': 4.576910928933754}
 2019-09-30 16:54:05,626 [prior] Evaluating prior at array([3.50370138e+00, 9.11204573e-01, 1.04126504e+00, 2.16219965e-02,
       1.41769808e-01, 3.09536246e-01, 1.00594525e+00, 9.98716428e-01,
       9.96986749e-01, 1.61104589e+02, 2.05155316e-01, 5.38622846e+00,
       6.76563140e+00, 1.38714895e+01, 1.06969527e+01, 2.08161734e+01,
       1.78539742e+02, 1.30092081e+02, 8.96066276e+01, 1.64542571e+02,
       8.46780047e+01, 4.90355091e-02, 3.78905027e-02, 7.12159068e-01,
       3.28393151e-01, 1.06080831e+00, 4.57691093e+00])
 2019-09-30 16:54:05,628 [prior] Got logpriors = [-52.7633457971763, -3.9407015400894174]
 2019-09-30 16:54:05,628 [likelihood] Got input parameters: OrderedDict([('As', 3.323825200880004e-09), ('ns', 0.9112045733967743), ('cosmomc_theta', 0.01041265037924763), ('ombh2', 0.021621996540981202), ('omch2', 0.14176980838432607), ('mnu', 0.06), ('tau', 0.3095362460289987), ('A_planck', 1.0059452468116512), ('calib_100T', 0.9987164276517926), ('calib_217T', 0.9969867491925797), ('A_pol', 1), ('calib_100P', 1.021), ('calib_143P', 0.966), ('calib_217P', 1.04), ('cib_index', -1.3), ('A_cib_217', 161.1045890924937), ('xi_sz_cib', 0.2051553164786664), ('A_sz', 5.386228462601731), ('ksz_norm', 6.765631397757046), ('gal545_A_100', 13.871489482728224), ('gal545_A_143', 10.6969527157267), ('gal545_A_143_217', 20.8161734334329), ('gal545_A_217', 178.5397415906308), ('A_sbpx_100_100_TT', 1), ('A_sbpx_143_143_TT', 1), ('A_sbpx_143_217_TT', 1), ('A_sbpx_217_217_TT', 1), ('ps_A_100_100', 130.0920806163113), ('ps_A_143_143', 89.60662764337052), ('ps_A_143_217', 164.5425707037178), ('ps_A_217_217', 84.67800468096046), ('galf_TE_index', -2.4), ('galf_TE_A_100', 0.0490355091419101), ('galf_TE_A_100_143', 0.037890502727434563), ('galf_TE_A_100_217', 0.7121590683248342), ('galf_TE_A_143', 0.328393151407387), ('galf_TE_A_143_217', 1.0608083053493131), ('galf_TE_A_217', 4.576910928933754), ('galf_EE_index', -2.4), ('galf_EE_A_100', 0.055), ('galf_EE_A_100_143', 0.04), ('galf_EE_A_100_217', 0.094), ('galf_EE_A_143', 0.086), ('galf_EE_A_143_217', 0.21), ('galf_EE_A_217', 0.7), ('A_cnoise_e2e_100_100_EE', 1), ('A_cnoise_e2e_143_143_EE', 1), ('A_cnoise_e2e_217_217_EE', 1), ('A_sbpx_100_100_EE', 1), ('A_sbpx_100_143_EE', 1), ('A_sbpx_100_217_EE', 1), ('A_sbpx_143_143_EE', 1), ('A_sbpx_143_217_EE', 1), ('A_sbpx_217_217_EE', 1)])
 2019-09-30 16:54:05,629 [camb] Computing (state 0)
 2019-09-30 16:54:05,629 [camb] Setting parameters: {'As': 3.323825200880004e-09, 'ns': 0.9112045733967743, 'cosmomc_theta': 0.01041265037924763, 'ombh2': 0.021621996540981202, 'omch2': 0.14176980838432607, 'mnu': 0.06, 'tau': 0.3095362460289987, 'halofit_version': 'mead', 'bbn_predictor': 'PArthENoPE_880.2_standard.dat', 'lens_potential_accuracy': 1, 'num_massive_neutrinos': 1, 'nnu': 3.046, 'theta_H0_range': [20, 100], 'H0': None, 'lmax': 2508}
 2019-09-30 16:54:05,645 [camb] Setting attributes of CAMBParams: {'WantTransfer': True, 'Want_CMB': True, 'NonLinear': 'NonLinear_lens'}
 2019-09-30 16:54:06,064 [planck_2018_lowl.TT] Got parameters {'A_planck': 1.0059452468116512}
 2019-09-30 16:54:06,064 [planck_2018_lowl.TT] Evaluated to logp=-47.1838 with derived {}
 2019-09-30 16:54:06,064 [planck_2018_lowl.EE] Got parameters {'A_planck': 1.0059452468116512}
 2019-09-30 16:54:06,071 [exception handler] ---------------------------------------

Traceback (most recent call last):
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/likelihood.py", line 129, in _logp_cached
    i_state = next(i for i in range(self.n_states)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lh561/.virtualenvs/py36env/bin/cobaya-run", line 11, in <module>
    load_entry_point('cobaya', 'console_scripts', 'cobaya-run')()
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/run.py", line 154, in run_script
    run(info)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/run.py", line 87, in run
    sampler.run()
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/sampler.py", line 182, in __exit__
    self.close(exception_type, exception_value, traceback)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/run.py", line 87, in run
    sampler.run()
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/samplers/polychord/polychord.py", line 233, in run
    self.pc_prior, self.dumper)
  File "/home/lh561/.virtualenvs/py36env/lib/python3.6/site-packages/pypolychord-1.16-py3.6-linux-x86_64.egg/pypolychord/__init__.py", line 231, in run_polychord
    settings.seed)
  File "/home/lh561/.virtualenvs/py36env/lib/python3.6/site-packages/pypolychord-1.16-py3.6-linux-x86_64.egg/pypolychord/__init__.py", line 192, in wrap_loglikelihood
    logL, phi[:] = loglikelihood(theta)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/samplers/polychord/polychord.py", line 218, in logpost
    self.model.logposterior(params_values))
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/model.py", line 280, in logposterior
    make_finite=make_finite, cached=cached, _no_check=True)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/model.py", line 186, in loglikes
    _derived=_derived, cached=cached)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/likelihood.py", line 360, in logps
    _derived=this_derived_dict, cached=cached, **this_params_dict)]
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/likelihood.py", line 146, in _logp_cached
    self.states[i_state]["logp"] = self.logp(_derived=_derived, **params_values)
  File "/home/lh561/Documents/Projects/CobayaPrj/cobaya/cobaya/likelihoods/_base_classes/_planck_clik_prototype.py", line 139, in logp
    loglike = self.clik(self.vector)[0]
  File "lkl.pyx", line 89, in clik.lkl.clik.__call__
clik.lkl.CError: <unprintable CError object>
-------------------------------------------------------------

 2019-09-30 16:54:06,071 [exception handler] Some unexpected ERROR occurred. You can see the exception information above.
We recommend trying to reproduce this error with 'debug:True' in the input.
If you cannot solve it yourself and need to report it, include the debug output,
which you can send it to a file setting 'debug_file:[some_file_name]'.
```

**Comment by JesusTorrado** [comment]
Thanks, @lukashergt 

I've identified the source of the error: a combination of a Python3 incompatibility with how Clik raises errors, and of Cobaya not dealing well with errors inside likelihoods. Working on it...

**Comment by JesusTorrado** [comment]
Should be fixed now.

Additionally, this fix adds a `stop_at_error` (default `False`) keyword to every likelihood. It behaves similarly as it does for theory codes: if `True`, does the obvious thing, and if `False` assigns 0 likelihood, prints the error info as debug info if requested, and goes on.

**Comment by jcolinhill** [comment]
Has this fix propagated to the latest pip-installable version?  I just re-installed/upgraded but am still seeing a similar bug (and it doesn't appear that the change to the source code is present, on a quick look).

**Comment by JesusTorrado** [comment]
It is now, as `v2.0.3`. Sorry: I was trying to finalise a couple of other bugs before deploying.

**Comment by jcolinhill** [comment]
No worries, thanks!
